name = 'HyNET Hugo Theme'
license = 'MIT'
licenselink = 'https://github.com/hyena-network/hugo-theme-hynet/LICENSE'
description = 'HyNET theme for Hugo for hyena.network'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/hyena-network/hugo-theme-hynet'

# If you have a running demo of the theme
demosite = 'https://hyena.network/'

# Taxonomy terms
tags = ['blog', 'company']
features = ['some', 'awesome', 'features']

# If the theme has a single author
[author]
  name = 'Mel'
  homepage = 'hyena.network'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'About me'
pageRef = '/about/'
weight = 15

[[menus.main]]
name = 'Services'
pageRef = '/services/'
weight = 20

[[menus.main]]
name = 'Blog'
pageRef = '/blog'
weight = 30

[[menus.main]]
name = 'Announcements'
pageRef = '/tags/announcement/'
weight = 40